/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContentTemplatesRouteImport } from './routes/content/templates'
import { Route as ContentShadcnRouteImport } from './routes/content/shadcn'
import { Route as ContentPackagesRouteImport } from './routes/content/packages'
import { Route as ContentHostingRouteImport } from './routes/content/hosting'
import { Route as ContentCoursesRouteImport } from './routes/content/courses'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentTemplatesRoute = ContentTemplatesRouteImport.update({
  id: '/content/templates',
  path: '/content/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentShadcnRoute = ContentShadcnRouteImport.update({
  id: '/content/shadcn',
  path: '/content/shadcn',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentPackagesRoute = ContentPackagesRouteImport.update({
  id: '/content/packages',
  path: '/content/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentHostingRoute = ContentHostingRouteImport.update({
  id: '/content/hosting',
  path: '/content/hosting',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentCoursesRoute = ContentCoursesRouteImport.update({
  id: '/content/courses',
  path: '/content/courses',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/submit': typeof SubmitRoute
  '/content/courses': typeof ContentCoursesRoute
  '/content/hosting': typeof ContentHostingRoute
  '/content/packages': typeof ContentPackagesRoute
  '/content/shadcn': typeof ContentShadcnRoute
  '/content/templates': typeof ContentTemplatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/submit': typeof SubmitRoute
  '/content/courses': typeof ContentCoursesRoute
  '/content/hosting': typeof ContentHostingRoute
  '/content/packages': typeof ContentPackagesRoute
  '/content/shadcn': typeof ContentShadcnRoute
  '/content/templates': typeof ContentTemplatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/submit': typeof SubmitRoute
  '/content/courses': typeof ContentCoursesRoute
  '/content/hosting': typeof ContentHostingRoute
  '/content/packages': typeof ContentPackagesRoute
  '/content/shadcn': typeof ContentShadcnRoute
  '/content/templates': typeof ContentTemplatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/submit'
    | '/content/courses'
    | '/content/hosting'
    | '/content/packages'
    | '/content/shadcn'
    | '/content/templates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/submit'
    | '/content/courses'
    | '/content/hosting'
    | '/content/packages'
    | '/content/shadcn'
    | '/content/templates'
  id:
    | '__root__'
    | '/'
    | '/submit'
    | '/content/courses'
    | '/content/hosting'
    | '/content/packages'
    | '/content/shadcn'
    | '/content/templates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SubmitRoute: typeof SubmitRoute
  ContentCoursesRoute: typeof ContentCoursesRoute
  ContentHostingRoute: typeof ContentHostingRoute
  ContentPackagesRoute: typeof ContentPackagesRoute
  ContentShadcnRoute: typeof ContentShadcnRoute
  ContentTemplatesRoute: typeof ContentTemplatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/templates': {
      id: '/content/templates'
      path: '/content/templates'
      fullPath: '/content/templates'
      preLoaderRoute: typeof ContentTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/shadcn': {
      id: '/content/shadcn'
      path: '/content/shadcn'
      fullPath: '/content/shadcn'
      preLoaderRoute: typeof ContentShadcnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/packages': {
      id: '/content/packages'
      path: '/content/packages'
      fullPath: '/content/packages'
      preLoaderRoute: typeof ContentPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/hosting': {
      id: '/content/hosting'
      path: '/content/hosting'
      fullPath: '/content/hosting'
      preLoaderRoute: typeof ContentHostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/courses': {
      id: '/content/courses'
      path: '/content/courses'
      fullPath: '/content/courses'
      preLoaderRoute: typeof ContentCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SubmitRoute: SubmitRoute,
  ContentCoursesRoute: ContentCoursesRoute,
  ContentHostingRoute: ContentHostingRoute,
  ContentPackagesRoute: ContentPackagesRoute,
  ContentShadcnRoute: ContentShadcnRoute,
  ContentTemplatesRoute: ContentTemplatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
